### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Thejus-M** [Martichou/rquickshare#1]
I am search for such a tool,but i don't know how to run this.Detailed documentation on the tool's usage would great. I appreciate the work, and please continue your excellent work.

**Comment by Martichou** [comment]
Hey ! As you can see this project was started a week ago. I first set up the ground base :)

I'll try to update the doc as the project goes, I'll update this issue once it has been added !

**Comment by Martichou** [comment]
I've added a quick how-to-use guide for the current state of the project. (https://github.com/Martichou/rquickshare/blob/master/README.md)

Know that when the project will be ready, there'll be a GUI and a self-install method for Linux.
Currently you'll have to follow the README if you really want to use the project in it's current status.
