### ISSUE TITLE
not able to send to android device, instructions in readme didn't help as intent can't be found in shortcut maker

### ISSUE THREAD

**Issue by akirapink** [Martichou/rquickshare#101]
i don't know if this would classify as a shortcut maker problem, but none of the ones i tried from the list of suggested shortcut makers could find either intent (`com.google.android.gms.nearby.sharing.ReceiveSurfaceActivity` or `com.google.android.gms.RECEIVE_NEARBY`)
notably, when trying to add it myself from the first suggested shortcut maker, i was prompted to choose an app to use that intent in, but the documentation here didn't point me towards any

Android 14, Samsung Galaxy A54

**Comment by rasyidrafi** [comment]
try to look inside the google play services, you ll find it there

**Comment by Martichou** [comment]
Samsung did some shady things with their QuickShare implementation. Unfortunately, there's no fix currently for that.. I'm sorry!

**Comment by skjnldsv** [comment]
@Martichou can you add this part to the Readme? I spend some time trying on my Samsung device before finding this thread :see_no_evil: :pray:

**Comment by Martichou** [comment]
Sure thing, I've added it :)

**Comment by Klusio19** [comment]
@Martichou I own Samsung Galaxy S24 with Android 14, and indeed, Samsung did something shady and both activities mentioned in the README cannot be found in the Shortcut Maker app.
BUT after randomly trying other similar activities, I found one working! It is in the Google Play Services app category and the full name of it is following: `com.google.android.gms.nearby.discovery.devices.FindDeviceActivity`.
After launching such shortcut, my phones shows in the rquickshare and stays visible for about 1-2 minutes and it works fully as expected.

**Comment by Martichou** [comment]
> @Martichou I own Samsung Galaxy S24 with Android 14, and indeed, Samsung did something shady and both activities mentioned in the README cannot be found in the Shortcut Maker app.

Hey! Thanks for letting me know. I'll add it in the README :)
However, this should not be required anymore if you have Bluetooth on your computer as it should now broadcast as "trying to send something".

**Comment by Klusio19** [comment]
> > @Martichou I own Samsung Galaxy S24 with Android 14, and indeed, Samsung did something shady and both activities mentioned in the README cannot be found in the Shortcut Maker app.
> 
> Hey! Thanks for letting me know. I'll add it in the README :) However, this should not be required anymore if you have Bluetooth on your computer as it should now broadcast as "trying to send something".

I have bluetooth on my computer, however it unfortunately didn't work.
