### ISSUE TITLE
distribution: add Nix channel 24.05 to README.md

### ISSUE THREAD

**Issue by Nerglej** [Martichou/rquickshare#107]
We should simply add to the README that the app is available on Nix unstable AND stable 24.05 channel.

I know I didn't do my research properbly (clicking the link, and switching to the channel I use), but I read the README and assumed I couldn't use it, since I'm on stable 24.05😅 But it's available there also so that's great.

Just wanted to mention it not being documented in this repo.

**Comment by Martichou** [comment]
Thanks for the info :)
