### ISSUE TITLE
Missing package libwebkit2gtk-4.0-37: Ubuntu 24.04

### ISSUE THREAD

**Issue by Haselnuss1** [Martichou/rquickshare#109]
Hey i can't install the .deb because the package libwebkit2gtk-4.0-37 is missing.

![Bildschirmfoto vom 2024-06-22 21-53-58](https://github.com/Martichou/rquickshare/assets/173572319/696193e9-1962-4c9f-9c2a-ddc27536087f)

to my knowledge, the package is not available in Ubuntu 24.04

maybe you can do anything to fix it, if not, don't worry about it 

PS: it's my first ever post on GitHub, sorry if something is missing and sorry that it's German

**Comment by Martichou** [comment]
Unfortunately for the moment I can't do anything. 
I'm working on a WIP for a no-gui version that would not depends on anything.
And I'm also planning on reworking the app to work with Tauri V2 (which will support 24.04 but not 20.04..).

So in the end my goal would be to have a no-gui (WIP), with a Tauri V1 (as long as I deemed it reasonnable) alongside with a Tauri V2 versions.
