### ISSUE TITLE
RPM release artifacts missing

### ISSUE THREAD

**Issue by craigcabrey** [Martichou/rquickshare#110]
> At the moment, only Deb, Rpm and AppImage are generated and supported.

However, I don't see any RPMs attached as release artifacts. Is there a broken pipeline?

**Comment by Martichou** [comment]
Indeed, it is not available anymore. It was present when I used Tauri V2, but since the switch back to Tauri V1 it is not.
However, I'll soon make a Tauri V2 version available to support Ubuntu 24.04+, so it shouldn't be that long of a wait. :)
