### ISSUE TITLE
Possible useful info 

### ISSUE THREAD

**Issue by alexandru0-dev** [Martichou/rquickshare#113]
First of all, I love the project
This repo may contain some useful info/implementation

https://github.com/bagel897/rustdrop

You would even try to contact the dev if you think it could help grow the project 

I really hope this project grows well :)

**Comment by Martichou** [comment]
Yeah I was already aware of that project :) Already chatted a bit with bagel897 but I can't do much as my BT chip is too old it seems. But thanks !
