### ISSUE TITLE
bug: macos display two icon in system tray

### ISSUE THREAD

**Issue by Martichou** [Martichou/rquickshare#115]
No idea why, if anyone have an idea, help me :)

<img width="81" alt="Screenshot 2024-07-04 at 21 35 31" src="https://github.com/Martichou/rquickshare/assets/23138751/8417ba8b-38bc-4148-b65d-b4c2c31604c6">

**Comment by JurianOnderwater** [comment]
https://github.com/tauri-apps/tauri/issues/9480

Might be related to this

**Comment by Martichou** [comment]
Thanks, haven't saw that!

Gonna test https://github.com/tauri-apps/tray-icon/pull/122/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

**Comment by Celibistrial** [comment]
Hey i think this is still an issue 
![image](https://github.com/user-attachments/assets/0473d163-4c35-4a3e-a759-fa9edaecf824)
