### ISSUE TITLE
feat: android version for non-GMS devices

### ISSUE THREAD

**Issue by Martichou** [Martichou/rquickshare#116]
Build an android app to allow non-GMS devices (for either custom ROMs or just de-googled devices) to use the QuickShare protocol.

(this is just an idea for now, but can be funny to build and useful, maybe?)

**Comment by lucasmz-dev** [comment]
I was gonna ask about this, Quick Share I wouldn't even consider an Android feature from it being GMS only. Do you know if this sounds possible (without priviliged permissions anyway)? or if there are any projects about this out there? I usually just use LocalSend, or Signal for other people.

**Comment by Martichou** [comment]
That's something possible, which is why it's on my roadmap. It won't be that well integrated as the real RQuickShare but will be as a standalone app :)

**Comment by Martichou** [comment]
Move to https://github.com/users/Martichou/projects/1
