### ISSUE TITLE
bug: not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by sk5268** [Martichou/rquickshare#120]
I've tried snap, .deb, appimage.
Neither my android can detect ubuntu, nor ubuntu can detect my android

I don't know whether this helps:
![image](https://github.com/Martichou/rquickshare/assets/120107598/8db30faf-9238-442f-b68e-2f59b81a2148)

**Comment by Martichou** [comment]
Can you try with the pre-release 0.9.0 named main? (not the legacy one)

Also:
- You can define the log level to TRACE for more output (might be useful to debug). 
See: https://github.com/Martichou/rquickshare/pull/104#issuecomment-2179485060
- Verify your firewall settings, you may block rquickshare.
- Your computer will only see your android device if you follow the workaround explained in the readme.
- Your android device should see your laptop if they are both on the same network, mDNS is not blocked and you're not set as "Hidden".
