### ISSUE TITLE
bug: unable to clear cancelled send to other rquickshare device

### ISSUE THREAD

**Issue by JurianOnderwater** [Martichou/rquickshare#123]
On mac
# Reproduce:
- Drag a file into the drag n drop box
- Select a device to send to (other device runs rquickshare, bug does not occur when sending to android device)
- click 'cancel'
- click 'clear' on the origin device, now it will go into sending again, sending notification/accept decline prompt to destination device again
- click 'cancel' again
- etc, viscious loop

sidenote, if you quit rquickshare on destination device while waiting for an accept/decline in this case, the origin device cancel button does not work anymore.

**Comment by Martichou** [comment]
Fixed first part in https://github.com/Martichou/rquickshare/commit/614bcbcdc63c771cbb2f513050f39d8aa703b7a1.
And second part in https://github.com/Martichou/rquickshare/commit/758ada81e30cc44ee92d985193a747bb1dc878b4.

Thanks for reporting.
