### ISSUE TITLE
bug: MacOS "RQuickShare is damaged and should be moved to trash"

### ISSUE THREAD

**Issue by hjgyuhuk** [Martichou/rquickshare#124]
I found a related issue on this topic that might be helpful.
[tauri/issues](https://github.com/tauri-apps/tauri/issues/8763)

**Comment by Martichou** [comment]
Thanks! Fixed in https://github.com/Martichou/rquickshare/commit/44de621f0d752c78e60a94b5bdb3298355e1eff7

**Comment by Martichou** [comment]
I did not face that, is it something "common" or that macOS guide the user correctly to fix the issue or should it be something in the README here?

**Comment by JurianOnderwater** [comment]
> I did not face that, is it something "common" or that macOS guide the user correctly to fix the issue or should it be something in the README here?

The right click in finder to open on the first startup goes for every app you download on a Mac from outside the appstore afaik. This is not an 'issue' with rquickshare or something that needs to be fixed, it's just a behaviour of macOS to keep people from installing dumb stuff.
