### ISSUE TITLE
Add an update notification

### ISSUE THREAD

**Issue by ffpp2003** [Martichou/rquickshare#126]
I was thinking that given the fact this app is under development and active work, a nice feature would be a "update available" notification that when opened, goes to the repo page for the user to download the new version

**Comment by Martichou** [comment]
I've added something like that two days ago, did you see it? Or maybe you're speaking about a real notification?
https://github.com/Martichou/rquickshare/commit/4710dae128608fd9d80abd23074920c63c1cf5ff

If it's the later, I don't think I'll add that. I'm not a big fan of applications sending notifications when there's no critical use. A visual information that a new update (which is what I've done) is enough for me :)

**Comment by ffpp2003** [comment]
Oh, nice, I didn't saw that. It was exactly what I was thinking about
