### ISSUE TITLE
bug: When a transfer from rquickshare to an android device is running, cancelling it isn't properly handled.

### ISSUE THREAD

**Issue by 103sbavert** [Martichou/rquickshare#128]
When a transfer initiated from a PC to an android phone is cancelled from the phone itself, it errors and says "Unexpected disconnection" after completely finishing the transfer (as opposed to stopping in the middle). It should instead inform the user the connection was cancelled.

Version: 0.10.1
OS: Arch Linux
AUR Package: r-quick-share (non-bin)

**Comment by Martichou** [comment]
You're sure the transfer did finish? That seems weird cause it should exit the loop directly.. or maybe the message isn't received 🤔 
Gonna check.

**Comment by Martichou** [comment]
Upon checking again, it seems like the Android device doesn't send a Cancelled packet for whatever reason...
But the transfer did stopped on my side. I've added a visual information (the circle will be full red if error/cancelled/rejected).
