### ISSUE TITLE
Support for Intel Mac

### ISSUE THREAD

**Issue by m-a-prod** [Martichou/rquickshare#131]
<img width="912" alt="image" src="https://github.com/user-attachments/assets/5885c477-78ae-4904-a2bf-7748885b9f67">

**Comment by JurianOnderwater** [comment]
It's built for m-series chips which have a different architecture compared to the Intel macs (hence why it says it's not supported). For Intel machines you can just build yourself using the instructions in the build.md and everything's works fine

**Comment by m-a-prod** [comment]
Yes, I know that. But I want the developers to make a version for Intel Mac in future releases.

**Comment by Martichou** [comment]
I'll check that. It can be done pretty easily if GitHub runners have macos with x86 arch.

**Comment by m-a-prod** [comment]
[RQuickShare_0.10.1_x64.dmg.zip](https://github.com/user-attachments/files/16198544/RQuickShare_0.10.1_x64.dmg.zip)

**Comment by Martichou** [comment]
Fixed in https://github.com/Martichou/rquickshare/commit/9709c52c26ab73fb07087e71a7ba0a6ab31c536a

This should be available in the next release :+1:
