### ISSUE TITLE
bug: Error with version 0.10.2

### ISSUE THREAD

**Issue by tokkenno** [Martichou/rquickshare#133]
I recently upgraded from version 0.10.1 to version 0.10.2 and now the application won't open.

When I start it via terminal, it throws the following error:

```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdk-0.18.0/src/auto/display.rs:301:9:
GDK has not been initialized. Call `gdk::init` or `gtk::init` first.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(process:13095): GLib-GIO-WARNING **: 11:13:56.539: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
```

Actual version: 0.10.2 (Installed via RPM)
Os: Fedora 40 (amd64)

**Comment by tokkenno** [comment]
The error seems to have been solved after restarting the computer. Maybe the process of the previous version was left in some weird state when exiting?

**Comment by Martichou** [comment]
Might be, still strange but gonna close this. Reopen if you face it again :)
