### ISSUE TITLE
feat: Hide from the Dock on macOS?

### ISSUE THREAD

**Issue by ryubellone** [Martichou/rquickshare#134]
Hi, I've been using "rquickshare" on Mac for a few minutes, and they are great.

Is there a way to hide the app from the Dock on macOS? It stays on the Dock while the window is closed. Some apps do support making the apps invisible from the Dock (mostly as the feature 'Hide from the Dock' or 'Show App in Dock'.)

And, any update for the 'changing device hostname' feature?

Thank you.

**Comment by Martichou** [comment]
Hey!

Just quickly answering both here, both are really good idea.
However I do not have a lot of time to work on new feature, so if anyone want to contribute, feel free!

I'm currently more focused on stability of RQuickShare and I'll work on the feature if I have enough time for it :)

**Comment by Martichou** [comment]
Moved to https://github.com/users/Martichou/projects/1/views/1
