### ISSUE TITLE
Galaxy doesn't detect the Mac and vice versa

### ISSUE THREAD

**Issue by Unsky-dev** [Martichou/rquickshare#137]
When I want to send a file to my Mac, QuickShare is launched and is always visible, but my Galaxy device cannot detect it. And if I try to send a file from my Mac to my Galaxy, it is also similar, the Mac does not display any device.

Mac: Macbook Air 2022 8gb (macos 15 public beta)
Galaxy: Samsung galaxy S20 FE 5G (Android 13, One UI 5.1)

**Comment by Martichou** [comment]
Hey!

Are you sure both devices are on the same network?
For macOS, you still need the workaround for your Android device to be seen by RQuickShare (see README).
But the other way around should work without issue, can you grab the log and send them?

**Comment by Unsky-dev** [comment]
Hii!

Yeah, both devices are on the same network.
I cannot launch the workarounds. The Files application no longer offers the Nearby share tab, and I have tried several shortcut applications, but none detect the specified actions in the README. I have also searched for a substitute, but I have not found one.

Where can I find the logs on my Mac?

**Comment by Martichou** [comment]
I guess it's in `./Library/Logs/dev.mandre.rquickshare/RQuickShare.log`

**Comment by Martichou** [comment]
Closing as not answer, ping if needed.
