### ISSUE TITLE
RPMs can't be used

### ISSUE THREAD

**Issue by james-pre** [Martichou/rquickshare#138]
The RPM on the latest release require glibc 2.39+, but all of the stable enterprise linux releases only package up to 2.34. With that, the RPM is really only usable on beta distros like CentOS stream 10.

I am able to use the legacy AppImage though, and have to say I'm really impressed. What a great project!

**Comment by Martichou** [comment]
Yeah sadly RPM bundle are only available on Tauri v2 which have min requirements. So this is a WON'T FIX sadly.

**Comment by james-pre** [comment]
@Martichou,

Thanks for the reply. Hopefully I'll be able to use the RPM when Rocky 10 comes out.
