### ISSUE TITLE
Compatibility with GLIBC 2.40

### ISSUE THREAD

**Issue by noahstreller** [Martichou/rquickshare#140]
Following is mentioned in the Readme:

![image](https://github.com/user-attachments/assets/41ac18de-5cb1-47af-92c2-a9fb304552c9)

The latest version of rquickshare does not work with the recently released glibc 2.40 yet.

![image](https://github.com/user-attachments/assets/a472fdd1-8ec7-4a02-ae24-52281de059b1)

**Comment by Martichou** [comment]
Which rquickshare have you installed? 
- r-quick-share-main_v0.10.2_glibc-2.39_amd64.deb
or
- r-quick-share-legacy_v0.10.2_glibc-2.31_amd64.deb

**Comment by noahstreller** [comment]
I have installed `r-quick-share-main_v0.10.2_glibc-2.39_amd64.deb`.

**Comment by Martichou** [comment]
Does the Appimage works in the meantime?

**Comment by noahstreller** [comment]
I receive this error when I try to run the AppImage:

![image](https://github.com/user-attachments/assets/ca4be4c9-8530-4804-a6d8-dc86154eb085)

![image](https://github.com/user-attachments/assets/45d2eca3-a897-4916-80a1-fa7b082e0459)

**Comment by Martichou** [comment]
It should be compatible as confirmed by one of the Tauri dev member. He also noted that it may be due to your installation (which seems to be custom as of the time of the issue, 2.40 was 1 day old).

A new release will be coming soon with updated Tauri, I'm hoping this would fix the issue.

**Comment by noahstreller** [comment]
Thanks for the update. Since my system shipped with an older version of GLibc (2.35), I attempted to build a more recent version of it. Is there a different, "more correct" way to obtain a recent GLibc version?

**Comment by Martichou** [comment]
I don't know, always used the default coming with the system or through "official" apt update.

You can test if the debug version here works for you: https://github.com/Martichou/rquickshare/actions/runs/10238289210
(if you prefer not to wait for the official release, bear in mind that those are debug variant :))

**Comment by Martichou** [comment]
Try https://github.com/Martichou/rquickshare/releases/tag/v0.11.0 and report if you face the issue again.

**Comment by noahstreller** [comment]
Due to running into a lot of issues after installing the custom GLibc 2.40, I had to remove it from my system 😐.

If anyone with a "healthy" installation wants to report their experience, feel free.

**Comment by Z1ni** [comment]
I tried the previous release main AppImage couple of weeks ago and it segfaulted, but the new 0.11.0 prerelease main AppImage works great.
My distro is Arch, so my system got glibc 2.40 pretty quickly.
