### ISSUE TITLE
assistance: which version to install for me?

### ISSUE THREAD

**Issue by zaxh-mp3** [Martichou/rquickshare#142]
hello i need video bc i dont know how to download it so please make a video bc im lost like what version of something like GLIBC or what so please make installation video thank you :)

**Comment by Martichou** [comment]
Hey! I'm sorry, if you're able to send me the output of `screenfetch` I'd be able to tell you which version to download. But making a video for that is not planned.

What is planned is a script install like some software for Linux out there, but that'll take some time.
