### ISSUE TITLE
feat: Add a "Start Minimized option"

### ISSUE THREAD

**Issue by TheDeadCell** [Martichou/rquickshare#143]
The settings menu includes an option to open on startup and an option to close to the system try instead of stopping the program.
Is it possible to add another setting to "Minimize on Boot" so that when starting on boot, rquickshare appears in the system tray, and no window appears?

**Comment by silvasch** [comment]
This is already being worked on: #55

**Comment by TheDeadCell** [comment]
My bad, I forgot to check the pull requests too. I'll close this issue. Duplicate of #55 .
