### ISSUE TITLE
bug: closing rquickshare, sgement violation.

### ISSUE THREAD

**Issue by jjsarton** [Martichou/rquickshare#147]
I have compiled the latest version from github under Fedora 40 XFCE.
The close button accessible via the Setting button don't work.
If I close rquickshare after I have transmitted a file via rquickshare, I get the following terminal output:

```
024-08-08T19:55:00Z ERROR rqs_lib::manager: TcpServer: error while handling client: early eof (Finished)
2024-08-08T19:55:21Z  INFO rqs_lib::hdl::blea: BleAdvertiser: tracker cancelled, returning
2024-08-08T19:55:21Z  INFO rqs_lib::hdl::mdns_discovery: MDnsDiscovery: tracker cancelled, breaking
2024-08-08T19:55:21Z  INFO rqs_lib::hdl::ble: BleListener: tracker cancelled, breaking
2024-08-08T19:55:21Z  INFO rqs_lib::manager: TcpServer: tracker cancelled, breaking
2024-08-08T19:55:21Z  INFO rqs_lib::hdl::mdns: MDnsServer: tracker cancelled, breaking
2024-08-08T19:55:21Z ERROR mdns_sd::service_daemon: Failed to send event: sending on a closed channel
2024-08-08T19:55:21Z  INFO rqs_lib::hdl::mdns: MDnsServer: service unregistered: OK
Aborted (core dumped)

```
The first  error message appear after the file was transferred.

If I close rquickshare without file transfer, there is no problem.

**Comment by Martichou** [comment]
Do you have the same issue with the latest available release ? I recently reworked the closing mechanism to be more streamlined, I don't see why it would segv tho (the rework is not yet released, that's why I'm asking)

**Comment by jjsarton** [comment]
I have installed the official rpm on an other system (r-quick-share-main_v0.10.2_glibc-2.39_1-x86_64.rpm) and also the official appImage on the test pc.
If I run the appimage no crash.
With the self compiled version which was rebuild today (2024-08-09),  the same problem.
The settings for rquickshare is:
```
Start on boot: disabled
Keep Running on close: disabled
Start minimized: disabled (only available on compiled version)
```
The difference between the official appImage and the self compiled version is the following.
The appImage remain running!
The self compiled version perform a crash if I close the window.

**Comment by Martichou** [comment]
Okay so can you confirm this:

The officially released version doesn't close when you close the app? But the master version will close (but segv)?

Could you gather some logs using the Trace level? https://github.com/Martichou/rquickshare/pull/104

**Comment by jjsarton** [comment]
[RQuickShare-close-abort.log](https://github.com/user-attachments/files/16571702/RQuickShare-close-abort.log)
[RQuickShare-close-ok.log](https://github.com/user-attachments/files/16571703/RQuickShare-close-ok.log)

Attached 2 files. For the file RQuickShare-close-abort.log, I selected a file to transmit and then canceled the action and closed the window.
The trace seem not to contain valuable informations.

**Comment by Martichou** [comment]
Could you try with the new pre-released version ? (v0.11.1).

**Comment by jjsarton** [comment]
> Could you try with the new pre-released version ? (v0.11.1).

I have compiled rquickshare from the master branch and also from release-please--branches--master.
in both cases rquickshare don't work as expected. 
If I try to send a file to an android smartphone, the left part of the GUI disappear and clicking on the name of the android device don't do anything.

**Comment by jjsarton** [comment]
I tried also the AppImage with libc 2.31 which work as expected. Against the 2.39 libc the self compiled or the AppImage don't work as expected and closing the window produce a core dump.

**Comment by Martichou** [comment]
Ok so you confirm that the AppImage with libc 2.31 is working just fine? If that's the case I'll close this issue as you have a stable version to use. 

There can be a multitude of reason why the other libc doesn't work on your system, that's why I released RQuickShare with two different targeted LIBC version.

Please confirm that the AppImage with 2.31 is working correctly.

**Comment by jjsarton** [comment]
I have also run the 2.39 AppImage on an mint 22 system, the problems are the same as the self compiled version as well as the rpm and appImage from github. 
The 2.31 AppImage work without the crash and the wrong layout.
