### ISSUE TITLE
AppImage crash at starting

### ISSUE THREAD

**Issue by jjsarton** [Martichou/rquickshare#156]
If I launch the file r-quick-share-main_v0.10.2_glibc-2.39_amd64.AppImage I got a crash.
Starting the binary contained within r-quick-share-main_v0.10.2_glibc-2.39_1-x86_64.rpm or 
r-quick-share-legacy_v0.10.2_glibc-2.31_amd64.AppImage work.

Running system Fedora 40 XFCE.

strace -e openat show that on 2.39 the file /tmp/.mount_r-quic######/RQuickShare.desktop is not present

**Comment by Martichou** [comment]
v0.11 should fix this, if not report back :)
