### ISSUE TITLE
deb Version not working

### ISSUE THREAD

**Issue by michal-gora** [Martichou/rquickshare#173]
I tried installing the "r-quick-share-main_v0.10.2_glibc-2.39_amd64.deb" release with 
sudo dpkg -i r-quick-share-main_v0.10.2_glibc-2.39_amd64.deb
however when trying to run the program, nothing happens. I tried the legacy deb version. There it does start, however the window is just blank.

**Comment by Martichou** [comment]
Do you have any logs? 

Does this helps? https://github.com/Martichou/rquickshare?tab=readme-ov-file#the-app-open-but-i-just-get-a-blank-window

(https://github.com/Martichou/rquickshare/issues/158)

**Comment by TheRealFame** [comment]
It was the same for me. I just used the legacy one, But even then i'm a bit stuck getting the actual window not to be blank.

**Comment by TheRealFame** [comment]
![image](https://github.com/user-attachments/assets/620cee5f-3739-4ed7-b862-0100b7cfe41f)
