### ISSUE TITLE
Feat: Add compatibility with Gear lever update feature.

### ISSUE THREAD

**Issue by goliv04053** [Martichou/rquickshare#183]
Gear Lever is an AppImage application manager. It got a feature which enables direct update from the app itself when there is an available link.

https://mijorus.it/posts/gearlever/update-url-info/

**Comment by Martichou** [comment]
AppImages are generated by Tauri. I'd like to keep it simple and let it as default to avoid handling everything manually.
As I see in the blog post, users can still add the URL from where to fetch the latest release themselves. So I'm going to close this issue as I won't do it.

Thanks for the suggestion, it was a great idea :)
