### ISSUE TITLE
bug: Error 71 (Protocol error) dispatching to Wayland display.

### ISSUE THREAD

**Issue by N0tACyb0rg** [Martichou/rquickshare#186]
On version `v0.11.2`, the application starts, then crashes with the error in the title.

I installed rquickshare from the [AUR](https://aur.archlinux.org/packages/r-quick-share) package.

Log (unsure how to enable verbose logging):
```
caleb@Gaia ~ [1]
❯ rquickshare
set_up_logging: level: Info
2024-08-30T03:54:21Z  INFO rqs_lib: TcpListener on: 0.0.0.0:45105
2024-08-30T03:54:21Z  INFO rqs_lib::manager: TcpServer: service starting
2024-08-30T03:54:21Z  INFO rqs_lib::hdl::mdns: Broadcasting with: Gaia
2024-08-30T03:54:21Z  INFO rqs_lib::hdl::ble: BleListener: service starting
2024-08-30T03:54:21Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
Gdk-Message: 20:54:22.528: Error 71 (Protocol error) dispatching to Wayland display.
```

System Information:
- OS: Arch Linux
- CPU: AMD Ryzen 7 5800X
- RAM: 64GB
- GPU: NVIDIA GeForce RTX 2080 Super (driver version 560.35.03)
- DE: KDE Plasma 6.1.4 (Wayland Session)
- Monitor (may be relevant?): KTC H34S18S, 3440x1440 @ 165 Hz with VRR enabled

**Comment by N0tACyb0rg** [comment]
Quick update after a bit of tinkering, running rquickshare with the suggestion for blank windows fixed the issue, but it still may be worth investigating.
`env WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare`

**Comment by Martichou** [comment]
I've already wasted some time on it and haven't found a fix for that.. 

I'm currently okay with the workaround as it does only affect a small portion of users. But indeed, if a fix is possible I'll implement it as soon as I find one.

**Comment by shayaknyc** [comment]
> Quick update after a bit of tinkering, running rquickshare with the suggestion for blank windows fixed the issue, but it still may be worth investigating. `env WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare`

I've updated the exec to include `'env WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare'` in the /usr/share/applications and ~/.local/share/applications Destkop shortcut, but it will only launch if I run this via CLI.....any ideas on what I may be doing wrong? I'm running plasma (wayland) on arch.....
