### ISSUE TITLE
 `GLIBC_2.39' not found (required by rquickshare)

### ISSUE THREAD

**Issue by harshads-dev** [Martichou/rquickshare#187]
rquickshare: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by rquickshare)

I Am Using Kali Linux, I Am Noob At this, Just learning how can i fix this problem?

**Comment by Martichou** [comment]
Have you tried the other binary? The 2.31 version legacy?

**Comment by harshads-dev** [comment]
> Have you tried the other binary? The 2.31 version legacy?

Brother, now its working thank you for your support 😊
