### ISSUE TITLE
Gdk-CRITICAL

### ISSUE THREAD

**Issue by iTomKo** [Martichou/rquickshare#188]
Hey!
I'm running latest (v0.11.2) r-quick-share on Arch Linux with i3wm.
Installed r-quick-share-bin from AUR.

I get this stacktrace when running from terminal:
`** (r-quick-share:1584292): WARNING **: 20:05:33.349: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
set_up_logging: level: Info
2024-09-01T18:05:33Z  INFO rqs_lib: TcpListener on: 0.0.0.0:46141
2024-09-01T18:05:33Z  INFO rqs_lib::manager: TcpServer: service starting
2024-09-01T18:05:33Z  INFO rqs_lib::hdl::mdns: Broadcasting with: archlinux
2024-09-01T18:05:33Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
Failed to create GBM buffer of size 553x1018: Invalid argument

(r-quick-share:1584292): Gdk-CRITICAL **: 20:05:33.536: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

Running the app results in systemtray, but empty window.

**Comment by iTomKo** [comment]
I'm a dummy,
the ..-bin version is outdated, will try the not compiled version.
Sorry :c

**Comment by Martichou** [comment]
Don't forget to close the issue if your issue is resolved :)
