### ISSUE TITLE
feat: website for RQuickShare

### ISSUE THREAD

**Issue by henriqueclaranhan** [Martichou/rquickshare#191]
I really liked the project and have started using it in my daily routine. I took the liberty of developing a simple download page for RQuickShare, similar to Google's page for [Quick Share](https://www.android.com/better-together/quick-share-app/).

You can view the website here: https://henriqueclaranhan.github.io/rquickshare/
Source code: https://github.com/henriqueclaranhan/rquickshare/tree/gh-pages

If you like it, feel free to modify and use it in the project.

**Comment by onezetty** [comment]
I really like this!!

**Comment by Martichou** [comment]
Hey! Thanks for your time. 

If you want to keep it up and maintains it it your fork feel free to do so, but sadly I won't do anything with it as I don't want to maintains a website in just pure HTML/CSS/JS. If I were to do one for RQuickShare I'd do it in Vue/Nuxt.

But it was a good idea! Thanks for that and keep it up :)
