### ISSUE TITLE
Rewrite frontend on Angular+Material

### ISSUE THREAD

**Issue by cookieman53** [Martichou/rquickshare#199]
I think the attached bundle would be better. Vue is more suitable for content-rich apps, not logic-rich ones. I can make a concept if you support my idea

**Comment by Martichou** [comment]
Hi, respectfully I will close this issue. I'm not planning on learning Angular.

But you're welcome to maintains your own fork of this project if you want, with any frontend you'd like. The core_lib is made for that purpose, it's "easy" to come and plug your superbe angular frontend suitable for logic-rich app on top :)

**Comment by jeena** [comment]
It's really cool that you made the core_lib available because if I had time I'd make a GNOME libadwaita version of this app, perhaps some day in the future.
