### ISSUE TITLE
distribution: AUR package

### ISSUE THREAD

**Issue by alba4k** [Martichou/rquickshare#21]
I could maintain this, if you want. I'd just need some instructions to build and install everything the intended way, and maybe a list of dependencies :)

**Comment by Martichou** [comment]
I guess you can get all the info you might want from the CI workflow (under .github/workflows) folder of this repo. 

Dependencies are installed before building.

**Comment by alba4k** [comment]
I'm confused about the part building the frontend

`pnpm deb:build` fails, probably because of the lack of a debian-like environnment. How could I only get a binary executable?

**Comment by Martichou** [comment]
Any logs of the fail? It shouldn't fails on a recent enough distro.

**Comment by alba4k** [comment]
Sorry for the delay.
`pnpm deb:build`

```
╰─ pnpm deb:build                                                                                                                                                                          ─╯

> rquickshare@0.1.0 deb:build /home/alba4k/Scaricati/rquickshare/frontend
> tauri build -b deb,appimage

sh: riga 1: tauri: comando non trovato
 ELIFECYCLE  Command failed.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by Martichou** [comment]
Please check https://github.com/Martichou/rquickshare/blob/master/BUILD.md :)

**Comment by alba4k** [comment]
that sounds great! I'll look into it later

**Comment by Martichou** [comment]
Thanks !

Also quick note: the License has been changed for GPL :)
I'm not sure I'll add that in the README as it's an unofficial pkg and it may be outdated (no auto sync I guess?)

**Comment by alba4k** [comment]
I can ad a rquickshare-git package which would pull from the latest commit on the main branch, if you want

**Comment by Martichou** [comment]
In the current form, will it be auto-updated if a new release is released?

**Comment by alba4k** [comment]
The maintainer would need to change a few lines of the pkgbuild. I'd expect it to be updated withing a couple of days

**Comment by Martichou** [comment]
Ok, I'll add it in a section for "unofficial way to install" or something like that :) Thanks
