### ISSUE TITLE
Failed to create GBM buffer of size 1800x1200: Invalid argument

### ISSUE THREAD

**Issue by alexandru-g** [Martichou/rquickshare#219]
rquickshare v0.11.2 (glibc-2.39) not launching correctly on Linux Mint 22 (white window). When launching from the terminal, it outputs this error:
`Failed to create GBM buffer of size 1800x1200: Invalid argument`

**Comment by Martichou** [comment]
Is the issue still present as you seemed to have a working app in #225 ?

**Comment by arut-plus** [comment]
> rquickshare v0.11.2 (glibc-2.39) not launching correctly on Linux Mint 22 (white window). When launching from the terminal, it outputs this error: `Failed to create GBM buffer of size 1800x1200: Invalid argument`

try ts:
```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 rquickshare
```
