### ISSUE TITLE
feat: macOS support

### ISSUE THREAD

**Issue by Dreamail** [Martichou/rquickshare#22]

**Comment by Martichou** [comment]
It might work, in theory everything should be ok except for the BLE part (I guess). But I don't have a Mac so it would be hard for me to test it.

**Comment by JurianOnderwater** [comment]
do you know the easiest way to remove all the ble/blea stuff? I'm trying to build for MacOS and that is the main issue atm

**Comment by Martichou** [comment]
I guess the easiest way would be to make all the BLE component in the core_lib to be only for not macos OS.

```
#[cfg(not(target_os = "macos"))]
```

Something like that to "hide" all the BLE code.

**Comment by JurianOnderwater** [comment]
Got it working on MacOS, removed all the ble code with `#[cfg(not(target_os = "macos"))]` and removed bluer from dependencies in cargo.toml

**Comment by Martichou** [comment]
> Got it working on MacOS, removed all the ble code with `#[cfg(not(target_os = "macos"))]` and removed bluer from dependencies in cargo.toml.
> Receiving works, but when sending the app cannot find any receivers.

It compiled and you're able to send and receive files?

**Comment by JurianOnderwater** [comment]
> > Got it working on MacOS, removed all the ble code with `#[cfg(not(target_os = "macos"))]` and removed bluer from dependencies in cargo.toml.
> > Receiving works, but when sending the app cannot find any receivers.
> 
> It compiled and you're able to send and receive files?

It compiled and I'm able to receive files, not send

**Comment by JurianOnderwater** [comment]
> > > Got it working on MacOS, removed all the ble code with `#[cfg(not(target_os = "macos"))]` and removed bluer from dependencies in cargo.toml.
> > > Receiving works, but when sending the app cannot find any receivers.
> > 
> > 
> > It compiled and you're able to send and receive files?
> 
> It compiled and I'm able to receive files, not send. Removed btleplug using #[cfg etc.] as well, just to be sure all bluetooth stuff was turned off. Will turn that back on and retry receiving later today.

adding back in btleplug and adding `markers = 'sys_platform != "macos"'` to bluers entry in Cargo.toml does compile and build, but upon opening the installed app, it immediately crashes

**Comment by thedroiddiv** [comment]
Thanks @JurianOnderwater adding support for macOS.

I applied all the changes suggested in the PR #44. Unfortunately, I wasn't able to get it working. None of my devices (Macbook air M1 and Pixel 6a) were able to discover each other. Are there any changes to latest branch which breaks this? I have compiled `master`.
Neither dev nor release build seems to work.

The only error I saw in logs is this, and there were a bunch of unused variable/import warnings.
```bash
error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
[0]  --> ../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/ed682dd/shared/template/Cargo.toml:2:8
[0]   |
[0] 2 | name = "tauri-plugin-{{name}}"
```

**Comment by Martichou** [comment]
I think the first thing is to still know that this PR is not finished I guess (as per warning and the BLE is disabled).

One step you can do to "debug", is enable tracing log.

```
env RQS_LOG=trace r-quick-share
```

You can send those here and I'll check. But I'm still going to try to get a mac to test myself.

**Comment by JurianOnderwater** [comment]
> Thanks @JurianOnderwater adding support for macOS.
> 
> I applied all the changes suggested in the PR #44. Unfortunately, I wasn't able to get it working. None of my devices (Macbook air M1 and Pixel 6a) were able to discover each other. Are there any changes to latest branch which breaks this? I have compiled `master`. Neither dev nor release build seems to work.
> 
> The only error I saw in logs is this, and there were a bunch of unused variable/import warnings.
> 
> ```shell
> error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
> [0]  --> ../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/ed682dd/shared/template/Cargo.toml:2:8
> [0]   |
> [0] 2 | name = "tauri-plugin-{{name}}"
> ```
> 
> And this
> 
> ```shell
> [0] 2024-05-18T15:27:21Z DEBUG rquickshare::logger: Finished setting up logging! yay!
> [0] 2024-05-18T15:27:21Z DEBUG rquickshare: Starting setup of RQuickShare app
> [0] 2024-05-18T15:27:21Z  WARN tauri_plugin_store: Failed to load store ".settings.json" from disk: No such file or directory (os error 2). Falling back to default values.
> [0] 2024-05-18T15:27:21Z TRACE rquickshare: Begining of RQS start
> [0] 2024-05-18T15:27:21Z  INFO rqs_lib: TcpListener on: 0.0.0.0:57359
> [0] 2024-05-18T15:27:21Z  INFO rqs_lib::hdl::mdns: Broadcasting with: macbook.local
> [0] 2024-05-18T15:27:21Z  INFO rqs_lib::manager: TcpServer: service starting
> [0] 2024-05-18T15:27:21Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
> [0] 2024-05-18T15:27:21Z DEBUG rqs_lib::hdl::mdns: MDnsServer: visibility changed: Visible
> ```

Seeing as you're a student, any chance you're testing on a university mesh network like eduroam? For me eduroam did not work at all but connecting my laptop to phone's hotspot, or just using it on my home network, it works just fine.

**Comment by JurianOnderwater** [comment]
`build.md` could be updated to build for macOS from app/main instead of app/legacy (for Intel models).

**Comment by Martichou** [comment]
thx, closing as [v0.9.0](https://github.com/Martichou/rquickshare/releases/tag/v0.9.0) is in preview with macos support for M processors.

**Comment by erfan226** [comment]
Hello,
Is there going to be a build for Intel Macs too?
Thanks.
