### ISSUE TITLE
Not starting properly from Gear Lever

### ISSUE THREAD

**Issue by alexandru-g** [Martichou/rquickshare#225]
First of all, amazing project!

I'm not sure if this is something supported by rquickshare, but I use Gear Lever to "install" AppImages so I have links created automatically (it's much easier).

Since recently, starting the app from Gear Lever presents an empty window:
![image](https://github.com/user-attachments/assets/b469bef6-ee54-45cf-9595-85e0a75b5c64)

Does rquickshare need some env variables or something?

**Comment by alexandru-g** [comment]
Yes, it does. After creating this ticket I installed the .deb package and that's working fine as well.

**Comment by Martichou** [comment]
You may want to open an issue with them then, if the AppImage is working fine as a standalone, I don't see why it doesn't work through some third-party software. I'm sure they would be of greater help than me on that :)

**Comment by arut-plus** [comment]
> Yes, it does. After creating this ticket I installed the .deb package and that's working fine as well.

try ts:
```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 rquickshare
```
