### ISSUE TITLE
Which version should I install?

### ISSUE THREAD

**Issue by DashFort02** [Martichou/rquickshare#226]
Hi, here is my screenfetch. What version of rquickshare should I put inside the curly braces when I execute:
`sudo snap install --dangerous r-quick-share_${VERSION}.snap`
![image](https://github.com/user-attachments/assets/2f902d3d-af92-477e-a5fb-2131166c1564)

**Comment by Martichou** [comment]
Try one and if it doesn't work try the other, I don't know which glibc you have installed and it doesn't take much times to try both.
