### ISSUE TITLE
Update readme about firewall blocking

### ISSUE THREAD

**Issue by uwuclxdy** [Martichou/rquickshare#229]
It currently says to open any port and specify it in the config manually but that doesn't work, since the config is overwritten at app launch. Rather than that, suggest users to open port 43813/tcp in their firewall, as that solved the issue for me.

Thanks for making this awesome program btw <3

**Comment by tanagno101** [comment]
I 've opened the port with "iptables -A INPUT -p tcp --dport 43813 -j ACCEPT" but cannot recieve files from smartphone.
I can send and I can see the laptop from my smartphone.

**Comment by Martichou** [comment]
> It currently says to open any port and specify it in the config manually but that doesn't work, since the config is overwritten at app launch. Rather than that, suggest users to open port 43813/tcp in their firewall, as that solved the issue for me.

What do you mean the config is overwritten? This shouldn't be the case, so that's the real issue here I think.
Opening a specific port doesn't help as the program will use a random port at runtime (in theory).

**Comment by Martichou** [comment]
I've just checked, and your issue was you probably added a comma at the end of the line when specifying port.
Read the updated README, it should works after that :)

https://github.com/Martichou/rquickshare?tab=readme-ov-file#my-firewall-is-blocking-the-connection
