### ISSUE TITLE
Not opening On kde neon: plasma 6

### ISSUE THREAD

**Issue by iamdanielsuresh** [Martichou/rquickshare#23]
1. Installed deb package
2. Tried opening via menu --> app loading but not opening

**Comment by Martichou** [comment]
Hey. Can you try running the .AppImage version and give me the logs ? 

You can do so by downloading the .AppImage and then:
```
chmod +x downloadedfile
./downloadedfile
```
(From a terminal)

You should see some logs inside the terminal, which may be helpful. If there's nothing interesting, I'll ask you to try with a debug build (log level is higher).

**Comment by iamdanielsuresh** [comment]
The problem solved after reboot. Now working perfectly.
