### ISSUE TITLE
Application opens up to a blank window. Both Appimage as well as the AUR version

### ISSUE THREAD

**Issue by simbasamba** [Martichou/rquickshare#240]
Hello,

I wanted to test this application but I couldn't get it to run. I first installed the unofficial AUR version but when I ran it the window was blank. Right-clicking brings up a menu where "Reload" and "Inspect element" are available but they don't do anything. I tried with the appimage version but the same issue happens there. Running from terminal spits this out:

```
set_up_logging: level: Info
2024-11-09T18:34:59Z  INFO rqs_lib: TcpListener on: 0.0.0.0:43893
2024-11-09T18:34:59Z  INFO rqs_lib::manager: TcpServer: service starting
2024-11-09T18:34:59Z  INFO rqs_lib::hdl::mdns: Broadcasting with: endeavour
2024-11-09T18:34:59Z  INFO rqs_lib::hdl::ble: BleListener: service starting
2024-11-09T18:34:59Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
Failed to create GBM buffer of size 900x600: Invalid argument
```

My OS info:

Operating System: EndeavourOS 
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B78
System Version: 1.0

P.S. I rarely report issues so I am not sure if I included all/relevant info. Let me know and I can provide more details. 

EDIT: I did some troubleshooting and tried with ` env WEBKIT_DISABLE_COMPOSITING_MODE=1` and managed to get the app to run.

EDIT2: App runs but I can't get the files to transfer. I tried sending files both to and from my Pixel 8 Pro but from PC to phone I don't see the phone at all in the app and the other way around I see the PC but it always fails.

From PC to phone error:
`ERROR mdns_sd::service_daemon: Failed to send SearchStarted(_FC9F5ED42C8A._tcp.local.)(repeating:true): sending on a closed channel
`

**Comment by Martichou** [comment]
Hey! 

Have you tried running it with the env variable specified in the README at this section? https://github.com/Martichou/rquickshare?tab=readme-ov-file#the-app-open-but-i-just-get-a-blank-window-or-cannot-run-it

**Comment by simbasamba** [comment]
Hey, maybe you missed my edit but I did try that and it did work but I have a new issue now that the share itself doesn't work. Thanks for the support!

**Comment by Martichou** [comment]
Have you checked that you don't have a firewall blocking communication?

**Comment by lkcv** [comment]
@simbasamba,
In firewalld, I had to whitelist mdns in order to see my phone, but not to receive files from it (that doesn't depend on mdns being allowed on your computer). To receive files from my phone, I had to just allow every port (TCP) and restrict that to my phone since the port that this app binds to when it starts always changes.

**Comment by Martichou** [comment]
You can specify which port the application will use in the config file, check the README for that :) 
This should fix your problem with the firewall.
