### ISSUE TITLE
blank window opening on linuxmint 22 (ubuntu24.04), mate desktop

### ISSUE THREAD

**Issue by sophana** [Martichou/rquickshare#249]
Hi

I tried both appImage and .deb version, launching rquickshare show an empty window, plus an icon in the notification area.

I have linuxmint mate 22, based on ubuntu24.04

**Comment by Martichou** [comment]
Have you checked the README?

https://github.com/Martichou/rquickshare?tab=readme-ov-file#the-app-open-but-i-just-get-a-blank-window-or-cannot-run-it

**Comment by kxmpxtxnt** [comment]
Hey, Im encountering the same error. When executing it with the env set it still does not work for me.

**Comment by Martichou** [comment]
Have you tried both the legacy and the main version? AppImage and regular? Both with and without the env?

**Comment by Martichou** [comment]
I see what you mean but as a open source project it may be difficult for me (as I know very well the project) to know what to explain in the README so a novice user understand it all..

So yeah, I can maybe come up with an update in the README but if you also have some time to propose an update to it in a PR, it's very much welcomed :)
