### ISSUE TITLE
distribution: flatpak package

### ISSUE THREAD

**Issue by HEx-404** [Martichou/rquickshare#26]
It'd be great to have a Flatpak version of this app as well, especially with rpm gone

**Comment by Martichou** [comment]
Hi! Tauri currenty doesn't support Flatpak. More info: [tauri-apps/tauri#3619](https://github.com/tauri-apps/tauri/issues/3619).

Unfortunately it seems complicated, so for the moment, please use the AppImage.

**Comment by rugk** [comment]
I agree! It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. They are easy to install _and_ update and work on all Linux distros.
Also, if you publish it on _FlatHub_ you may grow your user base given many distros include that and it is a common software source, so your app can be discovered more easily. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Comment by vvvvvvitor** [comment]
Apparently it's already working on Tauri V2RC!

https://v2.tauri.app/distribute/flatpak/

**Comment by rugk** [comment]
Well… the guide links to create a `.deb` build before, which is a stub (empty doc), so hmm… Also the link is wrong, opened https://github.com/tauri-apps/tauri-docs/issues/2501 about that.

**Comment by Martichou** [comment]
Moved to https://github.com/users/Martichou/projects/1/views/1
