### ISSUE TITLE
Please document building steps

### ISSUE THREAD

**Issue by pemensik** [Martichou/rquickshare#27]
This application seems to be exactly what I have been looking for. I would try to help with preparing rpm package for it, but I have not found almost none instructions, how the application should be build.

I have build core_bin, verified my Samsung phone can see it and offer upload. I stuck on pin verification.

But first should be at least rough documenting what tools are needed to compile existing code. After quick view into the repository, it is not obvious how the package should be build. Especially frontend does not contain any building steps I would recognize.

**Comment by Martichou** [comment]
If you have any more questions, don't hesitate to reopen :)
