### ISSUE TITLE
Unclear license / illegal to use software

### ISSUE THREAD

**Issue by edgarogh** [Martichou/rquickshare#29]
The AGPL says that when using the software over a network, the software source code must be made available to remote users.

> AGPLv3 requires a program to offer source code to “all users interacting with it remotely through a computer network.” It doesn't matter if you call the program a “client” or a “server,” the question you need to ask is whether or not there is a reasonable expectation that a person will be interacting with the program remotely over a network.
> https://www.gnu.org/licenses/gpl-faq.en.html#AGPLv3ServerAsUser

> For example, a Web proxy could use a landing page. When users initially start using the proxy, you can direct them to a page with the offer of source along with any other information you choose to provide.

How does this make sense for quickshare? Should rquickshare send its source code the first time it interacts with peer?

**Currently, running rquickshare as-is in a public setting is illegal** because someone might end up communicating with it, and they wouldn't get access to the source code.

I think it'd be great to clarify this point in the readme (or use another license).

**Comment by Martichou** [comment]
Hey ! Thanks for the info, I naively though it was enough that the source code was published on Github.

Considering this project is purely for the public and I do not intend to put any restrictions, I think it would be best to switch to the [MIT](https://opensource.org/license/mit) license.

**Comment by edgarogh** [comment]
Thanks for the clarification!

If you want a copyleft/free license, basic GPL would be a great fit, and it's usually a good choice in the Linux ecosystem. MIT works too but it's much more permissive, so you loose the "free software" aspect. It's really up to your preference.

Be careful, you'll have to ask other contributors if they are OK with the license change, since you'll basically be re-licensing their work too :wink:

**Comment by Aleksanaa** [comment]
Hi, I'm an annoying packager, and I need to point out your license is still unclear. Do you mean "GPL v3 only" or "GPL v3 or any later versions"?

**Comment by Martichou** [comment]
@Aleksanaa thanks for the question, the correct is "GPL v3 or any later versions".

As you seem to know a bit more about licensing than I do, may I ask you where I should put that information? Inside the License file? (I'm not too sure tbh)

**Comment by Aleksanaa** [comment]
1. Add it to your source code, see https://spdx.dev/learn/handling-license-info/
2. Mention it in README, like "This project is licensed under GPL version 3 or any later version"
