### ISSUE TITLE
Publish the core apart

### ISSUE THREAD

**Issue by leiserfg** [Martichou/rquickshare#37]
Thanks for your work. It will be nice to have access to the underlying logic (aka, not the ui) as a library so it can be used from a different UI toolkit. I don't wanna have to run another web browser just to share files.

**Comment by Martichou** [comment]
Hey! I understand and it's planned to release the crate as a standalone lib, but not currently. It's not ready to be used by someone else and is still subject to too many API changes.

But I also have on my roadmap a minimal application that would not have any UI, just relying on notification (like NearDrop) and maybe command line.

**Comment by Martichou** [comment]
Closing this one, I'll open a new one to implement a system tray only app with notification only. 

The core is not ready at all to be published as a standalone crate and won't be in the near future.
