### ISSUE TITLE
QuickShare protocol

### ISSUE THREAD

**Issue by DawidPietrykowski** [Martichou/rquickshare#39]
Hi, great project btw! I was personally working on something similar a few months ago: https://github.com/DawidPietrykowski/AirShare but I stopped due to concerns about changes to the protocol after Google's announcement. 

From what I see our implementations are quite similar and both are still working after the updates, but have you found any information about the changes that might happen? I'm just worried that a random update might break the compatibility that they temporarily left for now.

I also tried digging through the logs with logcat and here's some logs for the QuickShare transfer:
```
StartTransferParameters{shareId=16, requestId=5839926740895, transferType=NORMAL_SHARE, 
deviceInfo=AwareDeviceInfo{name : *****, targetIpAddress : ****:****:****:bc08%aware_data0, contactId : -1}, 
localInterfaceName=aware_data0, localIpAddress=****:****:****:5310%aware_data0, localDeviceName=******, 
parentFolder=, extras=[{serviceVersion=1, request_transfer_nondestructive_editing=false, request_transfer_transcoding=false, 
deviceId=********, serviceFeature=59, share_update_time=**********, FSAProtocol=null, request_transfer_preview=false, 
mediaCapability=11, }], openOutboundIntent=PendingIntent{9383c99: android.os.BinderProxy@6be9b5e}, listener=nc.c0@dd87d73}]
```

and here for the NearbyShare:
```
ShareLive  I  [SLog][main][MainViewModel] processing viewEvent: ClickMainModel(mainModel=Device(deviceItem=Device(device=Device(id=55, deviceId='12', shareId='c9096b92-9b0f-4353-b192-cb17ceea5796', deviceName='*******', deviceType=LAPTOP, deviceCategory=ANONYMOUS, 
connectionType=NEARBY_SHARE, isConnected=false, shareStatus=NONE, contactId=, displayName='*******', pinCode=, requestId=0, fileSentCount=0, fileCancelledCount=0, fileFailedCount=0, fileSendingCount=0, fileTotalCount=0, fileTotalSize=0, 
fileOnProgressSize=0, deviceCapability=[NEARBY_SHARE], data=, isRemoved=false, errorCode='', updateTime=*******, serviceName=NEARBY_SHARE, buddyId=null, acceptResult=NONE, mediaCapability=11, transcodingStatus=NONE, 
transcodingProgress=0, transferRequestId=0, localIp=null, peerIp=null, networkInterfaceName=null, isUwbDevice=false, angleOfArrival=0.0, distance=0.0, isBuddyCategory=false, cloudDownloadStatus=NONE, cloudFileTotalCount=0, 
cloudFileDownloadedCount=0, bluetoothAddress=null, isSession=false, encryptStatus=NONE, response=0, selectedResponse=0, isPrivacyTransfer=false, receiverPrivacyNumber=, expireDate=0, fsaProtocol=),
 profileUri=content://com.samsung.android.app.sharelive.profile/contact?size=150&displayName=*******, placeHolder=2131231415, _rectType=BOTTOM_FIRST)))
```

**Comment by Martichou** [comment]
Hey! Damnit, should have saw your project before.. would have prevented some headache :)

Tbh, I've not looked much into this problematic as it may or may not even be an issue in the future.
So for the moment, I'm happy for as long as it keeps working. And if it ever breaks due to an update (which is highly doubt), I'll just update/fix to support the new update. 

Quick note as to why I don't think this would happens for now: if it were to happens, it would already have. Google have full control over GMS and have the possibility to get rid of the old NearbyShare if they wanted to. Things is, QuickShare is interoperable with NearbyShare by design.
