### ISSUE TITLE
Use QNearbyShare?

### ISSUE THREAD

**Issue by 103sbavert** [Martichou/rquickshare#41]
Just an idea to reduce duplication of efforts. QNearbyShare is a CLI tool which can be used maybe by this project. I don't know Rust otherwise I'd have helped. Btw, it looks like you use Flutter? I am not sure but if you do, I just wanna mention GTK bindings for Rust also exist.

**Comment by Martichou** [comment]
Hey! So just to answer your points:
- no, I do not use Flutter for this project. I use Tauri with Vite and VueJS.
- Regarding QNearbyShare, I'm aware of this project as per the Credits in my README. But using it would bring a lot of complexity to this project (cmake, C++, ...) without being able to easily update it myself (I'm not so fluent in C++).

The goal of rquickshare is to be a complete and (almost) full featured implementation of the NearbyShare/QuickShare protocol in Rust mainly for Linux and (maybe) macOS (https://github.com/Martichou/rquickshare/pull/31).

**Comment by 103sbavert** [comment]
Noted. Btw, sharing wifi connections with quickshare fails as of rn. If you want, I will make a new issue.

**Comment by Martichou** [comment]
Yes, please do :)
