### ISSUE TITLE
feat: start minimized

### ISSUE THREAD

**Issue by KibSquib48** [Martichou/rquickshare#45]
I have rquickshare set to start on login and I'd like to be able to make it start with the window minimized/hidden

**Comment by Martichou** [comment]
I don't have much time to work on this for now so if someone else is willing to take it feel free.
(Tauri doesn't support this, so there may be a fair bit of work)

**Comment by bedantadey17** [comment]
+ 1
hugely needed feature. the reason i still use this in linux is because i love quick share. if only there was a dark mode + start minimised option this would be perfect.

**Comment by tatejuan12** [comment]
Hey, sorry for being MIA. I'll work on it this week!

**Comment by Martichou** [comment]
https://github.com/Martichou/rquickshare/commit/eac7dab0dcd8b609cd021f7f29d1e558dca4472c
