### ISSUE TITLE
Project naming

### ISSUE THREAD

**Issue by yochananmarqos** [Martichou/rquickshare#46]
As far as I've seen, Rust projects are named with an `-rs` suffix. R program language projects are prefaced with the `r-` prefix. 

Perhaps `quick-share-rs`?

**Comment by Martichou** [comment]
Hey! Yeah usually Rust projects have -rs as a suffix. However, this doesn't bother me and the project has already been release as it is. 

So I don't think I'm going to change the name anytime soon :) (but good catch, it was indeed an inattention from me)
