### ISSUE TITLE
Rule for FirewallD?

### ISSUE THREAD

**Issue by DiamivaeBro** [Martichou/rquickshare#48]
FirewallD blocking quick share by default
I think rule for firewalld can make installation easier because after install you need to manually create rule

**Comment by Martichou** [comment]
Hey! As this project aims to support a wide range of linux distribution and soon macOS, I won't add anything specific to a particular external program.

You'll have to configure your firewall manually. I can't support all firewall options available out there.

**Comment by liskin** [comment]
firewalld is not "a particular external program". It's **the** way for apps to interact with the firewall on a desktop Linux.

Also, how exactly are we meant to set up a firewall rule manually if rquickshare chooses the port to listen to at random?

**Comment by liskin** [comment]
It'd be fine if there was an option (command-line or in settings) to specify the port manually so it's always the same…

**Comment by Martichou** [comment]
Oh got it ! I forgot that the port was random :)
I'll add a setting to define a specific port.

**Comment by NiffirgkcaJ** [comment]
I think UFW is blocking this program for me.
