### ISSUE TITLE
The size of widgets for transfers after the first is off

### ISSUE THREAD

**Issue by alba4k** [Martichou/rquickshare#49]
![immagine](https://github.com/Martichou/rquickshare/assets/84153269/5989e510-de36-4b5e-8d4b-b9fbb93d9bc7)

**Comment by Martichou** [comment]
Indeed! Will fix that in the next release (prolly next week)

**Comment by Martichou** [comment]
Should be addressed in https://github.com/Martichou/rquickshare/commit/3597da86e16dd58e2f608112dc44ccd71aef061d.

Waiting for a new release before closing this issue.
