### ISSUE TITLE
Google account login?

### ISSUE THREAD

**Issue by HironTez** [Martichou/rquickshare#50]
I really like this app. This is what I've been looking for.

Do you have any plans to add Google Account synchronisation to have a 'my devices' visibility option and be able to send files to other devices that have that visibility option enabled?

**Comment by intelQong** [comment]
Tbh, I've never found my device when I'm on "Your Devices". So keeping only "Everyone" visibility is productive. 

@HironTez

**Comment by Martichou** [comment]
Hey! It should be possible but that would be a HUGEEE work.
So if someone is willing to work on it feel free, but personally, I won't bother with Google Account synchronisation in the near future.
