### ISSUE TITLE
Empty window when opening rquickshare

### ISSUE THREAD

**Issue by Rainb0-0** [Martichou/rquickshare#53]
Hello. When I try to launch the app, it shows an empty window as follows :
![image](https://github.com/Martichou/rquickshare/assets/85252899/bd9ed98a-87b4-4c75-804f-def09b9e6d0b)

here is the output of `uname -a` :
`Linux rainb0-0 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux`

And I'm using the latest version found in the releases page, specifically the Appimage one.

And here are the logs :

```
2024-03-25T06:23:35.048331Z  INFO rqs_lib: TcpListener on: 0.0.0.0:38839    
2024-03-25T06:23:35.071703Z  INFO rqs_lib::manager: TcpServer: service starting    
2024-03-25T06:23:35.080550Z  INFO rqs_lib::hdl::ble: BleListener: service starting    
2024-03-25T06:23:35.085208Z  INFO rqs_lib::hdl::mdns: Broadcasting with: rainb0-0    
2024-03-25T06:23:35.091988Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting    

(process:8523): Gtk-WARNING **: 09:53:35.182: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:8561): Gtk-WARNING **: 09:53:37.383: Locale not supported by C library.
	Using the fallback 'C' locale.
Could not create EGL context.

** (r-quick-share:8523): WARNING **: 09:54:02.116: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by Martichou** [comment]
Does closing (killing it) and reopening change anything?
Is the service working even with the widow black? 
You should be able to send a file to your computer and a notification should pop up allowing you to accept or reject it.

**Comment by Rainb0-0** [comment]
Thanks for your response.

> Does closing (killing it) and reopening change anything?

No it doesn't.

> Is the service working even with the widow black?

I don't think so, the laptop doesn't show up on my phone

However, after some deep digging, I found this issue in tauri's repo, which suggested using `WEBKIT_DISABLE_COMPOSITING_MODE=1` when launching the app, which seemed to resolve the issue, so I don't think that this issue is related to this project.

**Comment by Martichou** [comment]
Thanks for looking at this.
I'd check a bit more in depth what this WEBKIT_DISABLE_COMPOSITING_MODE is and if it make any sense to include it by default in the build process (if possible).

**Comment by Martichou** [comment]
Conclusion: will close as this is not even a bug in Tauri but in webkit. Nothing I can do here sadly.
