### ISSUE TITLE
errors building frontend

### ISSUE THREAD

**Issue by jjsarton** [Martichou/rquickshare#56]
rquikjshare: v 0.5.0

While building rquickshare I get the folllowing error message
```
dist/assets/index-kr7qkrb2.js   107.33 kB │ gzip: 35.37 kB
✓ built in 2.05s
error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
 --> ../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/ed682dd/shared/template/Cargo.toml:2:8
  |
2 | name = "tauri-plugin-{{name}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^
  |
   Compiling proc-macro2 v1.0.78

...

Bundling r-quick-share_0.5.0_amd64.AppImage (/home/$USER/rquickshare/frontend/src-tauri/target/release/bundle/appimage/r-quick-share_0.5.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh
 ELIFECYCLE  Command failed with exit code 1.
```
r-quick-share is present under rquickshare/frontend/src-tauri/target/release.
Of course the appimage is not present.

Build on Fedora 39 XFCE.

----------------

I have experimented a little bit.
- intalled quick share for windows from google on an windows 11 machine
- started r-quick-share
- selected a file to share

The android devices appeared on r-quick-share

- disabled bluetooth on windows

The The android devices disappear on r-quick-share

reenabled bluetooth on Windows

android devices appeared again on r-quick-share

**Comment by Martichou** [comment]
The log you have doesn't show why the bundling failed. The 'invalid character' is a warning that shouldn't cause the build to fail.
Is there a particular reason you're trying to bundle it yourself instead of either using the dev version (cargo) or the released version?

**Comment by jjsarton** [comment]
The provided appimage tell:

```
Gtk-Message: 13:51:35.411: Failed to load module "xapp-gtk3-module"
```

Due to this I tried to generate r-quick-share myself.

**Comment by Martichou** [comment]
Seems like it's a warning:

- https://bbs.archlinux.org/viewtopic.php?id=263690
- https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module
