### ISSUE TITLE
Couldn't init BleAdvertiser: Bluetooth operation failed: Failed

### ISSUE THREAD

**Issue by 103sbavert** [Martichou/rquickshare#59]
This is the error that appears when I open r-quick-share from the terminal and try to send a file to my phone

**Comment by Martichou** [comment]
The whole BLE (advertisement) is WIP for now. It does not have any impact on the software.
The only things is that if you don't use one of the workaround in the [README](https://github.com/Martichou/rquickshare?tab=readme-ov-file#my-laptop-doesnt-see-my-android-device), your computer won't be able to "see" your phone.

I'll close it as it's a known limitation for know, I still have to figure out how to send BLE advertisement correctly.
