### ISSUE TITLE
Make a snap version

### ISSUE THREAD

**Issue by Master811129** [Martichou/rquickshare#63]
Hello, Thanks for developing this. Could you please make a snap package for it?

**Comment by Martichou** [comment]
Next version should provide a .snap to install. I've decided to not publish it on the snapstore yet, but will do soon enough.

**Comment by Martichou** [comment]
https://github.com/Martichou/rquickshare/pull/65

**Comment by Martichou** [comment]
Done: https://github.com/Martichou/rquickshare/commit/13236db08b672466b967bbe1766f1ce613a7e33d

Will be available with 0.7.0 :)

**Comment by Master811129** [comment]
@Martichou `rquickshare` is already available in AUR. Could you please also add it to the [Snap Store](https://snapcraft.io/store) as-well?
