### ISSUE TITLE
Gnome Quick Setting Tile support

### ISSUE THREAD

**Issue by rodrigoswz** [Martichou/rquickshare#68]
A toggle on GNOME's Quick Settings Panel just like Zorin Connect (KDE Connect fork) to quickly set modes of RQuickShare.

![image](https://github.com/Martichou/rquickshare/assets/14058427/9eb5735e-f2e6-4ce7-aa52-5add14a1781f)

Btw it's exactly how it works with Quick Share on Android :)

**Comment by Martichou** [comment]
Hi, thanks for the suggestion. Although I'm not willing to spend time on this currently, someone may want to do it, so keeping this issue up in case :)

**Comment by brug-dev** [comment]
I don't think this is possible. I've only ever seen Gnome extensions be able to add to the quick settings tile, and since this is a separate app and not a gnome extension it's impossible without also developing a completely separate extension component.
