### ISSUE TITLE
Snap mentioned in README.md but asset not available

### ISSUE THREAD

**Issue by killua-eu** [Martichou/rquickshare#71]
Hi, th readme mentions that the snap can be installed manually with `snap install --dangerous r-quick-share_${VERSION}_amd64.snap` but the snap package isnt in the assets. Would you mind adding it to the CICD pipeline?
Thanks in advance, br, Pavel

**Comment by Martichou** [comment]
Oops, might have been an issue. It should have been added in 0.7.0.
I'll check that once I'm on a computer.

**Comment by killua-eu** [comment]
Cool, tested, on ubuntu 24.04, work perfectly. The snap package complains on install about 

```2024-05-02T08:32:33+02:00 INFO snap "r-quick-share" has bad plugs or slots: dbus (cannot find
attribute 'bus')```

..never packaged snaps, but perhaps https://github.com/Martichou/rquickshare/blob/master/snap/snapcraft.yaml#L16 should be `bus` and not `dbus` if I read https://snapcraft.io/docs/dbus-interface correctly

**Comment by Martichou** [comment]
Maybe you're right, I tried with what https://snapcraft.io/docs/supported-interfaces said (`dbus`), I'll check, but as you saw, it's not critical :)

**Comment by killua-eu** [comment]
yup, def not critical. just noticed it and ig it might eventually get in the way of having it published in the store ...
