### ISSUE TITLE
Parts of the UI need `user-select: none;` property

### ISSUE THREAD

**Issue by Master811129** [Martichou/rquickshare#81]
### Parts of the UI need `user-select: none;` and `-webkit-user-select: none;` CSS property. like `<p>`, `span` or `<h1|2|3|4|5>`, etc.

![Screenshot_20240506_141031](https://github.com/Martichou/rquickshare/assets/37829730/afce4227-d310-45f0-9a36-d0e127eb78c3)

![Screenshot_20240506_141109](https://github.com/Martichou/rquickshare/assets/37829730/38b9f597-4ea0-4011-88db-1c4f3a72306f)

**Comment by Martichou** [comment]
Could you draft a PR with those changes? It's a basic vue app in the frontend/src.
Cause I do not have such artefact on any of my laptops :/

**Comment by Master811129** [comment]
> Could you draft a PR with those changes?

Sorry, I really don't know how vue works.🙁
I only know plain HTML/CSS

``` css
h1 h2 h3 h4 h5 span p {
    user-select:none;
    -webkit-user-select:none; 
    corsor: default;
}
```

> I do not have such artefact on any of my laptops :/

You can get this artifact by selecting elements with the mouse. 

[Screencast_20240507_133254.webm](https://github.com/Martichou/rquickshare/assets/37829730/21bfa047-796e-497a-a2c2-730f80e149e6)

**Comment by Martichou** [comment]
https://github.com/Martichou/rquickshare/commit/3ae1396f05cd9e97e3775adc46b9c2b204ff2104
