### ISSUE TITLE
feat: add way to rename device

### ISSUE THREAD

**Issue by bruglet** [Martichou/rquickshare#87]
I'm loving the project so far and I believe it's actually the only way to get Nearby/Quick Share working on Linux!

However, would it be possible to add a method to rename the broadcasted name of the device?

**Comment by RayTF** [comment]
+1

**Comment by Martichou** [comment]
Moved to https://github.com/users/Martichou/projects/1/views/1

**Comment by IS2511** [comment]
So... How do you rename your device? Without changing the hostname. I'm on `v0.11.5`.
