### ISSUE TITLE
feat: add auto-accept for known devices

### ISSUE THREAD

**Issue by sfussenegger** [Martichou/rquickshare#89]
I'm predominantly sharing stuff with myself (phone to desktop), so having to click "Accept" all the time is quite unnecessary in my opinion.

Having an "Always accept" option would be great. There would have to be an option to remove these known devices too.

**Comment by Martichou** [comment]
Hey! I gave this a second though recently and I don't think this is a good idea anymore. 

Let me explain: as RQuickShare doesn't have any device authentication feature like Google (they can know that you own X or Y devices trying to share with you through your Google Account), there would be no way to guarantee that a device saying "Hey I'm your phone trust me", it really the one saying that. There's no way to guarantee that, and as such, I'm not ok with adding such a "security hole" in RQuickShare. If you think I'm wrong and there's a way to do it securely, feel free to help me on this one, but as it is, I'm going to close it as WON'T DO. But thanks anyway for the proposition :)

**Comment by sfussenegger** [comment]
I don't know enough about the inner workings of the protocol or the app to really comment on that. But if there's no way to tell if a device really is the device it claims to be it's probably the prudent thing to do. It might not be too bad if your're in a somewhat controlled environment - say a desktop in a home or office network - but that might substantially reduces the amount of users this is actually useful to.

**Comment by nemkin** [comment]
I'm not familiar with the protocol itself either, but would it be possible to do this on trusted networks? I trust all devices on my home wifi network.
