### ISSUE TITLE
process stays after closing window 

### ISSUE THREAD

**Issue by yxd0018** [Martichou/rquickshare#92]
Linux  6.5.0-35-generic #35~22.04.1-Ubuntu 
close the app by closing the window via top right icon but the process still running and further launching the app does nothing.

**Comment by yxd0018** [comment]
version 0.7.1

**Comment by yxd0018** [comment]
no issue as there is a config in setting for this behavior

**Comment by Martichou** [comment]
Yep, indeed, the config is present for this reason specifically :) glad you found it!
