### ISSUE TITLE
not able to see android

### ISSUE THREAD

**Issue by yxd0018** [Martichou/rquickshare#93]
From app "activity launcher", there is no com.google.android.gms.nearby.sharing.ReceiveSurfaceActivity but there is InternalReceiveSurfaceActivity. But it won't make android 13 device shown from r-quickshare.

**Comment by Martichou** [comment]
Can you share a screenshot of what you see on your android device once you trigger the InternalReceiveSurfaceActivity?
It should be something like this:
![Screenshot_20240605-113819](https://github.com/Martichou/rquickshare/assets/23138751/427807e3-1e21-4ecf-a6d3-70a347d10de6)
