### ISSUE TITLE
Not able to install it to my device (Ubuntu)

### ISSUE THREAD

**Issue by manab-debnath** [Martichou/rquickshare#94]
Showing the below error
![Screenshot from 2024-06-03 23-46-30](https://github.com/Martichou/rquickshare/assets/84611056/47828069-ae8d-48c7-941e-3d4753161225)

**Comment by haryp2309** [comment]
Try:

```sh
sudo apt update
sudo apt install ./r-quick-share_0.7.1_amd4. deb
```

**Comment by Martichou** [comment]
If it still doesn't work, use the AppImage for the moment. Tauri have some compatibility restriction and I'm working on a nogui version which should be way more compatible.
