### ISSUE TITLE
opens/runs on boot; fails to operate properly if closed and then attempted to be ran again

### ISSUE THREAD

**Issue by hellsober** [Martichou/rquickshare#96]
Worked perfectly after initial install. Opens on startup but if closed, it does not open visually (PC appears as a device to share to on other devices, but there is no indication on the PC that the program is running) and files are unable to be sent to PC. When the PC is selected on another device to share to, it immediately fails and reopening rQuickShare makes the PC appear again as a new device to select. On the sharer's side the PC option then goes grey claiming that it's screen is off. See picture attached. 
Running Linux Mint 21.3 and kernel 6.5

![59289](https://github.com/Martichou/rquickshare/assets/165501741/cc1309f4-27d3-4494-9cf6-20eacae48df7)

**Comment by Martichou** [comment]
Ok so it's not really clear what happens. Does it work correctly if you just open it and keep it open?
Also can you check in the settings if you allow it to keep running after closing the window?
