### ISSUE TITLE
feat: build for ARM64

### ISSUE THREAD

**Issue by palexdev** [Martichou/rquickshare#97]
Hello, I have an Android tablet which I modded to run Linux, would it be possible to build images for aarch64 too?

**Comment by Martichou** [comment]
That should be possible, I'll check that once I have some time :)

**Comment by Martichou** [comment]
Now waiting for github actions to release runners with ARM64 for Linux :)

**Comment by palexdev** [comment]
Great, I can finally ditch SendAnywhere (which is good to be fair but less practical)
Thank you very much

**Comment by Martichou** [comment]
Oh yeah forgot that you can probably already build it for yourself :)
The release package is waiting for github runner, but in the meantime you can build it manually 👍 

I'll close this issue once the runner is available.

**Comment by palexdev** [comment]
I don't know why but I can't build it
![PXL_20240706_190554395.jpg](https://github.com/Martichou/rquickshare/assets/16880178/8526fab3-04bc-4da2-a22b-90c4ffcee87e)

**Comment by Martichou** [comment]
Wtf, that's not even at compilation.. it's literally just the dependencies install that failed. 

Seems like an issue with pnpm/nodejs on your side. I compiled it yesterday on an ARM64 server without issue if I remember correctly (or maybe there was one at the very end while making the appimage, not sure).

Can you:
- check your nodejs/pnpm install
- if the issue persists, send me the output(log) as text so I can better see what's happening.

**Comment by palexdev** [comment]
Half success. Turned out the `pnpm` installed by `pacman` was outdated
![Screenshot from 2024-07-06 22-49-07](https://github.com/Martichou/rquickshare/assets/16880178/fc772e49-4710-4f5b-b7a4-a68bd5f749e4)
It seems that because of that bluethooth error it can't discover any device
(the other error may be because the wifi died tempprarily)

**Comment by Martichou** [comment]
I just pushed another commit to use a correct service_data for BLEA. Still seems like it doesn't works for me...
You need to use the workaround specified in the README (I let you check that) for your laptop to see your android.

(note: bluetooth is WIP, that's why you have an issue :))

**Comment by Martichou** [comment]
Update: I finally got it to work thanks to https://github.com/Martichou/rquickshare/commit/2a58a53eb0c1b92d8e3dc370ca044261f01a9356.
You still need to set the QuickShare visibility to Everyone on your android phone, but now it seems to works :partying_face:

**Comment by palexdev** [comment]
Fantastic!
![Screenshot from 2024-07-07 13-05-32](https://github.com/Martichou/rquickshare/assets/16880178/9c015c54-de77-4b49-af65-e2b98940a901)

**Comment by Martichou** [comment]
Moved to https://github.com/users/Martichou/projects/1/views/1
