### ISSUE TITLE
Not able to send to Android device

### ISSUE THREAD

**Issue by julianpollmann** [Martichou/rquickshare#99]
I'm able to receive files on my android -> laptop, however not able to send from laptop -> android.
Both devices have Bluetooth enabled, quick share setting on android is enabled for everyone for 10 minutes.

Testing with Android 14, LineageOS 21 with Pixel 2.

**Comment by Martichou** [comment]
Does this answer your issue? https://github.com/Martichou/rquickshare?tab=readme-ov-file#my-laptop-doesnt-see-my-android-device
